# Generated by Django 4.1.7 on 2023-04-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordify', '0004_article_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extratext',
            old_name='description',
            new_name='extratext',
        ),
    ]
